import path from 'node:path';
import { unlink } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

export const uploadsDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../uploads');

export function relativeUploadPath(filePath) {
  const relative = path.relative(uploadsDirectory, path.resolve(filePath));
  if (!relative || relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error('The uploaded file path is outside the uploads directory.');
  }
  return relative.split(path.sep).join('/');
}

export function absoluteUploadPath(storedPath) {
  const normalized = String(storedPath || '').replaceAll('\\', '/');
  const segments = normalized.split('/');
  // Stored paths are generated by this service and are always simple relative
  // segments. Reject Windows drive/ADS syntax as well as traversal so an
  // unexpected legacy database value can never change the resolved root.
  if (!normalized || normalized.startsWith('/') || path.isAbsolute(normalized) || path.win32.isAbsolute(normalized) ||
    segments.some(segment => !segment || segment === '.' || segment === '..' || segment.includes(':'))) return null;
  const absolute = path.resolve(uploadsDirectory, ...segments);
  return absolute.startsWith(`${uploadsDirectory}${path.sep}`) ? absolute : null;
}

export async function deleteStoredFiles(storedPaths) {
  for (const storedPath of new Set((storedPaths || []).filter(Boolean))) {
    const absolute = absoluteUploadPath(storedPath);
    if (!absolute) continue;
    try {
      await unlink(absolute);
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
}

// Disk cleanup happens after the database transaction commits. A cleanup
// failure must not make callers retry an already-completed update.
export async function cleanUpCommittedFiles(storedPaths, context) {
  try {
    await deleteStoredFiles(storedPaths);
  } catch (error) {
    console.error(`Could not remove stale ${context}:`, error);
  }
}

export function storedFileUrl(storedPath) {
  if (!absoluteUploadPath(storedPath)) return null;
  return `/uploads/${String(storedPath).replaceAll('\\', '/').split('/').map(encodeURIComponent).join('/')}`;
}
