import path from 'node:path';
import { readFile, unlink } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import pool from '../config/db.js';

export const uploadsDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../uploads');

function configuredUploadStorage() {
  const value = String(process.env.WAIS_UPLOAD_STORAGE || 'filesystem').trim().toLowerCase();
  if (value === 'filesystem' || value === 'database') return value;
  throw new Error('WAIS_UPLOAD_STORAGE must be either "filesystem" or "database".');
}

export function usesDatabaseUploadStorage() {
  return configuredUploadStorage() === 'database';
}

export const MAX_DATABASE_UPLOAD_BYTES = 10 * 1024 * 1024;

export function relativeUploadPath(filePath) {
  const relative = path.relative(uploadsDirectory, path.resolve(filePath));
  if (!relative || relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error('The uploaded file path is outside the uploads directory.');
  }
  return relative.split(path.sep).join('/');
}

export function absoluteUploadPath(storedPath) {
  const normalized = String(storedPath || '').replaceAll('\\', '/');
  const segments = normalized.split('/');
  // Stored paths are generated by this service and are always simple relative
  // segments. Reject Windows drive/ADS syntax as well as traversal so an
  // unexpected legacy database value can never change the resolved root.
  if (!normalized || normalized.startsWith('/') || path.isAbsolute(normalized) || path.win32.isAbsolute(normalized) ||
    segments.some(segment => !segment || segment === '.' || segment === '..' || segment.includes(':'))) return null;
  const absolute = path.resolve(uploadsDirectory, ...segments);
  return absolute.startsWith(`${uploadsDirectory}${path.sep}`) ? absolute : null;
}

function validStoredPaths(storedPaths) {
  return [...new Set((storedPaths || []).filter(storedPath => absoluteUploadPath(storedPath)))];
}

// The database store keeps uploaded evidence durable on hosts where the local
// filesystem is ephemeral (for example a Render Free web service). The disk
// remains a short-lived upload staging area; the BLOB and its metadata commit
// atomically in the same database transaction.
export async function persistUploadedFile(connection, storedPath, file, tenantId, owner) {
  if (!usesDatabaseUploadStorage()) return;
  if (!absoluteUploadPath(storedPath)) throw new Error('The uploaded file path is invalid.');
  if (!Number.isSafeInteger(Number(tenantId)) || Number(tenantId) < 1) throw new Error('The upload tenant is invalid.');
  const fileId = Number(owner?.fileId);
  const attachmentId = Number(owner?.attachmentId);
  const hasFileOwner = Number.isSafeInteger(fileId) && fileId > 0;
  const hasAttachmentOwner = Number.isSafeInteger(attachmentId) && attachmentId > 0;
  if (hasFileOwner === hasAttachmentOwner) throw new Error('The uploaded file owner is invalid.');
  const contents = await readFile(file?.path || '');
  if (contents.length !== Number(file?.size) || contents.length > MAX_DATABASE_UPLOAD_BYTES) {
    throw new Error('The uploaded file could not be stored safely.');
  }
  const contentSha256 = createHash('sha256').update(contents).digest();
  await connection.execute(
    `INSERT INTO upload_blobs (path, tenant_id, file_id, attachment_id, content, content_size, content_sha256)
      VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [storedPath, Number(tenantId), hasFileOwner ? fileId : null, hasAttachmentOwner ? attachmentId : null, contents, contents.length, contentSha256]
  );
}

export async function loadStoredFile(storedPath, tenantId, owner) {
  if (!usesDatabaseUploadStorage() || !absoluteUploadPath(storedPath)) return null;
  const fileId = Number(owner?.fileId);
  const attachmentId = Number(owner?.attachmentId);
  const hasFileOwner = Number.isSafeInteger(fileId) && fileId > 0;
  const hasAttachmentOwner = Number.isSafeInteger(attachmentId) && attachmentId > 0;
  if (hasFileOwner === hasAttachmentOwner) return null;
  const [rows] = await pool.execute(
    `SELECT content FROM upload_blobs WHERE path = ? AND tenant_id = ?
      AND ${hasFileOwner ? 'file_id = ?' : 'attachment_id = ?'} LIMIT 1`,
    [storedPath, Number(tenantId), hasFileOwner ? fileId : attachmentId]
  );
  return rows[0]?.content ?? null;
}

export async function deleteStoredFiles(storedPaths) {
  const paths = validStoredPaths(storedPaths);
  for (const storedPath of paths) {
    const absolute = absoluteUploadPath(storedPath);
    try {
      await unlink(absolute);
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
}

// Disk cleanup happens after the database transaction commits. A cleanup
// failure must not make callers retry an already-completed update.
export async function cleanUpCommittedFiles(storedPaths, context) {
  try {
    await deleteStoredFiles(storedPaths);
  } catch (error) {
    console.error(`Could not remove stale ${context}:`, error);
  }
}

export async function cleanUpTemporaryUpload(storedPath, context) {
  if (!usesDatabaseUploadStorage()) return;
  await cleanUpCommittedFiles([storedPath], context);
}

export function storedFileUrl(storedPath) {
  if (!absoluteUploadPath(storedPath)) return null;
  return `/uploads/${String(storedPath).replaceAll('\\', '/').split('/').map(encodeURIComponent).join('/')}`;
}
